'use client'

import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type MenuItem={id:string;name:string;description:string;price_cop:number;category:string;sort_order:number;image_url:string|null}

export default function Home(){
  const supabase=useMemo(()=>createClient(),[]);const [table,setTable]=useState<{id:string,label:string}|null>(null);const [menu,setMenu]=useState<MenuItem[]>([]);const [notice,setNotice]=useState('');const [loading,setLoading]=useState(false)
  useEffect(()=>{supabase.from('menu_items').select('id,name,description,price_cop,category,sort_order,image_url').eq('available',true).order('sort_order').order('name').then(({data})=>setMenu((data||[]) as MenuItem[]));const token=new URLSearchParams(window.location.search).get('mesa');if(!token)return;supabase.rpc('get_table_by_token',{token}).then(({data})=>{if(data?.[0])setTable(data[0]);else setNotice('Este QR no está activo. Pide ayuda al equipo.')})},[supabase])
  async function request(type:'waiter'|'bill'){if(!table){setNotice('Escanea el QR asignado a tu mesa para solicitar atención.');return}setLoading(true);const {error}=await supabase.from('service_requests').insert({table_id:table.id,table_token:new URLSearchParams(window.location.search).get('mesa'),type});setLoading(false);setNotice(error?'No pudimos enviar la solicitud. Intenta de nuevo.':type==='waiter'?'El mesero recibió tu solicitud.':'La cuenta fue solicitada para tu mesa.')}
  return <><header className="header"><a className="brand" href="#inicio"><img src="/yarumo-logo.png" alt="Yarumo Coffee"/><span><strong>Yarumo</strong><small>COFFEE</small></span></a><a href="https://www.instagram.com/yarumocafearmenia/" target="_blank" rel="noreferrer">Instagram ↗</a></header><main id="inicio"><section className="hero"><span className="eyebrow">Café de origen · Armenia</span><h1>Más que café,<br/><em>momentos.</em></h1><p>Abre tu carta, pide la cuenta o llama al mesero sin levantarte de la mesa.</p></section><section className="service"><div className="service-card"><div><span className="eyebrow">{table?`Mesa ${table.label}`:'Menú digital'}</span><h2>Todo desde tu celular.</h2><p>Sin esperas. Toca una opción y el equipo recibe la solicitud.</p></div><div className="service-actions"><button className="primary" onClick={()=>request('waiter')} disabled={loading}>♧ Llamar al mesero</button><button onClick={()=>request('bill')} disabled={loading}>Pedir la cuenta</button></div></div></section><section className="content"><span className="eyebrow">La carta</span><h2>Elige tu momento.</h2><div className="menu">{menu.length?menu.map(item=><article className="item" key={item.id}>{item.image_url&&<img className="item-image" src={item.image_url} alt={item.name} loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/>}<h3>{item.name}</h3><p>{item.description}</p><small>{new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(item.price_cop)}</small></article>):<p>Cargando carta…</p>}</div></section><footer className="footer"><span>Yarumo Coffee · Carrera 19 # 21 Norte-01</span><span><a href="https://www.google.com/search?q=Yarumo+Coffee+Armenia" target="_blank" rel="noreferrer">Reseñas de Google ↗</a> · <a href="https://www.instagram.com/yarumocafearmenia/" target="_blank" rel="noreferrer">Redes ↗</a></span></footer></main>{notice&&<button className="notice" onClick={()=>setNotice('')}>{notice} ×</button>}</>
}
