'use client'

import { useEffect, useState } from 'react'

type User = { id: string; email?: string; lastSignInAt?: string | null; profile: { display_name: string; role: string } | null }
const empty = { email: '', password: '', displayName: '', role: 'staff' }

export default function UserAdmin() {
  const [users, setUsers] = useState<User[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<User | null>(null); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  async function load() { const response = await fetch('/api/admin/users', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) { setMessage(data.error || 'No se pudieron cargar los usuarios'); return }; setUsers(data) }
  useEffect(() => { load() }, [])
  function startEdit(user: User) { setEditing(user); setForm({ email: user.email || '', password: '', displayName: user.profile?.display_name || '', role: user.profile?.role || 'staff' }) }
  function reset() { setEditing(null); setForm(empty) }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(''); const response = await fetch('/api/admin/users', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editing ? { id: editing.id, displayName: form.displayName, role: form.role, password: form.password || undefined } : form) }); const data = await response.json(); setSaving(false); if (!response.ok) { setMessage(data.error || 'No se pudo guardar'); return }; reset(); load() }
  async function remove(user: User) { if (!confirm(`¿Eliminar el usuario ${user.email || ''}?`)) return; const response = await fetch(`/api/admin/users?id=${encodeURIComponent(user.id)}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) setMessage(data.error || 'No se pudo eliminar'); else load() }
  return <section className="user-admin"><div className="menu-admin-head"><div><span className="eyebrow">Accesos</span><h2>Usuarios del equipo.</h2></div><button className="button" onClick={reset}>+ Nuevo usuario</button></div>{message && <p className="admin-error">{message}</p>}<div className="user-grid"><div className="admin-list">{users.map(user => <article className="admin-item" key={user.id}><div><strong>{user.profile?.display_name || user.email}</strong><small>{user.email} · {user.profile?.role || 'sin perfil'}</small></div><div><button onClick={() => startEdit(user)}>Editar</button><button onClick={() => remove(user)}>Eliminar</button></div></article>)}</div><form className="menu-form" onSubmit={save}><h3>{editing ? 'Editar usuario' : 'Nuevo usuario'}</h3>{!editing && <input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="Correo" required />}{editing && <input value={form.email} readOnly aria-label="Correo del usuario" /> }<input value={form.displayName} onChange={e => setForm({ ...form, displayName: e.target.value })} placeholder="Nombre" required /><input type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder={editing ? 'Nueva contraseña (opcional)' : 'Contraseña, mínimo 10 caracteres'} minLength={editing ? 0 : 10} required={!editing} /><select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}><option value="staff">Staff</option><option value="manager">Manager</option><option value="owner">Owner</option></select><div><button className="button" type="submit" disabled={saving}>{saving ? 'Guardando…' : 'Guardar usuario'}</button>{editing && <button type="button" onClick={reset}>Cancelar</button>}</div></form></div></section>
}
